name: "spectr-action"
description: "GitHub Action for spec-driven development validation using Spectr."
author: "conneroisu"

inputs:
  version:
    description: "The version of Spectr to use, e.g., '0.1.0'. Defaults to 'latest'."
    required: false
    default: "latest"

  checksum:
    description: "The checksum of the spectr version to install"
    required: false

  github-token:
    description: "Used to increase the rate limit when retrieving versions and downloading spectr."
    required: false
    default: ${{ github.token }}

  strict:
    description: "Treat warnings as errors (enables --strict mode). Set to 'false' to ignore warnings."
    required: false
    default: "true"

outputs:
  spectr-version:
    description: "The version of Spectr that was installed and used"

runs:
  using: "node20"
  main: "dist/spectr-action/index.js"

branding:
  icon: "check-circle"
  color: "blue"
