package archive

import (
	"fmt"
	"strings"
)

// buildCommitMessage generates the commit message for the archive.
// It creates a formatted commit message with change ID, archive location,
// and spec operation counts if applicable.
func buildCommitMessage(ctx PRContext) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("Archive: %s\n\n", ctx.ChangeID))
	sb.WriteString(
		fmt.Sprintf(
			"Completed change '%s' archived to changes/archive/%s/\n",
			ctx.ChangeID,
			ctx.ArchiveName,
		),
	)

	if !ctx.SkipSpecs && ctx.OpCounts.Total() > 0 {
		sb.WriteString("\nSpec operations applied:\n")
		sb.WriteString(fmt.Sprintf("+ %d added\n", ctx.OpCounts.Added))
		sb.WriteString(fmt.Sprintf("~ %d modified\n", ctx.OpCounts.Modified))
		sb.WriteString(fmt.Sprintf("- %d removed\n", ctx.OpCounts.Removed))
		sb.WriteString(fmt.Sprintf("→ %d renamed\n", ctx.OpCounts.Renamed))
	}

	sb.WriteString(fmt.Sprintf("\nChange-Id: %s\n", ctx.ChangeID))

	return sb.String()
}

// buildPRTitle generates the PR title from change ID.
// Returns a formatted title string "Archive: {change-id}".
func buildPRTitle(changeID string) string {
	return fmt.Sprintf("Archive: %s", changeID)
}

// buildPRBody generates the PR body description.
// It creates a detailed markdown body showing archive summary, spec updates,
// and review notes for the pull request.
func buildPRBody(ctx PRContext) string {
	var sb strings.Builder

	sb.WriteString("## Archive Summary\n\n")
	fmt.Fprintf(&sb, "Archived completed change: `%s`\n\n", ctx.ChangeID)
	fmt.Fprintf(
		&sb,
		"Location: `spectr/changes/archive/%s/`\n\n",
		ctx.ArchiveName,
	)

	sb.WriteString("## Spec Updates\n\n")
	switch {
	case ctx.SkipSpecs:
		sb.WriteString("Spec updates skipped (--skip-specs flag used)\n\n")
	case ctx.OpCounts.Total() > 0:
		sb.WriteString("Spec operations applied:\n")
		fmt.Fprintf(&sb, "- **+ %d added**\n", ctx.OpCounts.Added)
		fmt.Fprintf(&sb, "- **~ %d modified**\n", ctx.OpCounts.Modified)
		fmt.Fprintf(&sb, "- **- %d removed**\n", ctx.OpCounts.Removed)
		fmt.Fprintf(&sb, "- **→ %d renamed**\n\n", ctx.OpCounts.Renamed)

		writeCapabilities(&sb, ctx.Capabilities)
	default:
		sb.WriteString("No spec updates (no delta specs found)\n\n")
	}

	writeReviewNotes(&sb)

	return sb.String()
}

// writeCapabilities appends capability list to the string builder.
// It writes a formatted list of capabilities that were updated.
func writeCapabilities(sb *strings.Builder, capabilities []string) {
	if len(capabilities) == 0 {
		return
	}

	sb.WriteString("Updated capabilities:\n")
	for _, cap := range capabilities {
		fmt.Fprintf(sb, "- `%s`\n", cap)
	}
	sb.WriteString("\n")
}

// writeReviewNotes appends review notes section to the string builder.
// It adds a standard review checklist for archive PRs.
func writeReviewNotes(sb *strings.Builder) {
	sb.WriteString("## Review Notes\n\n")
	sb.WriteString(
		"This PR archives a completed change and updates " +
			"specifications to reflect the implemented functionality. " +
			"Please review:\n",
	)
	sb.WriteString("1. Archived change structure and completeness\n")
	sb.WriteString("2. Spec delta accuracy and correctness\n")
	sb.WriteString("3. Merged spec content\n\n")

	sb.WriteString("---\n")
	sb.WriteString("Generated by `spectr archive --pr`\n")
}
