package archive

import (
	"strings"
	"testing"
)

func TestBuildCommitMessage(t *testing.T) {
	tests := []struct {
		name string
		ctx  PRContext
		want []string // Strings that should be in the message
	}{
		{
			name: "with spec updates",
			ctx: PRContext{
				ChangeID:    "test-change",
				ArchiveName: "2025-11-20-test-change",
				SkipSpecs:   false,
				OpCounts: OperationCounts{
					Added:    3,
					Modified: 1,
					Removed:  0,
					Renamed:  0,
				},
			},
			want: []string{
				"Archive: test-change",
				"Completed change 'test-change'",
				"changes/archive/2025-11-20-test-change/",
				"Spec operations applied:",
				"+ 3 added",
				"~ 1 modified",
				"- 0 removed",
				"→ 0 renamed",
				"Change-Id: test-change",
			},
		},
		{
			name: "with skip specs",
			ctx: PRContext{
				ChangeID:    "test-change",
				ArchiveName: "2025-11-20-test-change",
				SkipSpecs:   true,
				OpCounts:    OperationCounts{},
			},
			want: []string{
				"Archive: test-change",
				"Completed change 'test-change'",
				"changes/archive/2025-11-20-test-change/",
				"Change-Id: test-change",
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := buildCommitMessage(tt.ctx)

			for _, want := range tt.want {
				if !strings.Contains(got, want) {
					t.Errorf(
						"buildCommitMessage() missing expected string:\n  want: %q\n  got: %q",
						want,
						got,
					)
				}
			}

			// Skip specs should not have spec operations section
			if tt.ctx.SkipSpecs && strings.Contains(got, "Spec operations applied:") {
				t.Error(
					"buildCommitMessage() should not contain spec operations when SkipSpecs=true",
				)
			}
		})
	}
}

func TestBuildPRTitle(t *testing.T) {
	tests := []struct {
		name     string
		changeID string
		want     string
	}{
		{
			name:     "simple change ID",
			changeID: "test-change",
			want:     "Archive: test-change",
		},
		{
			name:     "multi-word change ID",
			changeID: "add-new-feature",
			want:     "Archive: add-new-feature",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := buildPRTitle(tt.changeID)
			if got != tt.want {
				t.Errorf("buildPRTitle() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestBuildPRBody(t *testing.T) {
	tests := []struct {
		name string
		ctx  PRContext
		want []string // Strings that should be in the body
	}{
		{
			name: "with spec updates and capabilities",
			ctx: PRContext{
				ChangeID:    "test-change",
				ArchiveName: "2025-11-20-test-change",
				SkipSpecs:   false,
				OpCounts: OperationCounts{
					Added:    3,
					Modified: 1,
					Removed:  0,
					Renamed:  0,
				},
				Capabilities: []string{"auth", "payments"},
			},
			want: []string{
				"## Archive Summary",
				"Archived completed change: `test-change`",
				"Location: `spectr/changes/archive/2025-11-20-test-change/`",
				"## Spec Updates",
				"Spec operations applied:",
				"- **+ 3 added**",
				"- **~ 1 modified**",
				"- **- 0 removed**",
				"- **→ 0 renamed**",
				"Updated capabilities:",
				"- `auth`",
				"- `payments`",
				"## Review Notes",
				"Generated by `spectr archive --pr`",
			},
		},
		{
			name: "with skip specs",
			ctx: PRContext{
				ChangeID:    "test-change",
				ArchiveName: "2025-11-20-test-change",
				SkipSpecs:   true,
			},
			want: []string{
				"## Archive Summary",
				"Archived completed change: `test-change`",
				"## Spec Updates",
				"Spec updates skipped (--skip-specs flag used)",
				"## Review Notes",
				"Generated by `spectr archive --pr`",
			},
		},
		{
			name: "no spec updates found",
			ctx: PRContext{
				ChangeID:    "test-change",
				ArchiveName: "2025-11-20-test-change",
				SkipSpecs:   false,
				OpCounts:    OperationCounts{},
			},
			want: []string{
				"## Archive Summary",
				"## Spec Updates",
				"No spec updates (no delta specs found)",
				"## Review Notes",
				"Generated by `spectr archive --pr`",
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := buildPRBody(tt.ctx)

			for _, want := range tt.want {
				if !strings.Contains(got, want) {
					t.Errorf(
						"buildPRBody() missing expected string:\n  want: %q\n  in: %q",
						want,
						got,
					)
				}
			}

			// Check that skip specs doesn't show operations
			if tt.ctx.SkipSpecs && strings.Contains(got, "Spec operations applied:") {
				t.Error("buildPRBody() should not contain operations when SkipSpecs=true")
			}
		})
	}
}

func TestOperationCountsTotal(t *testing.T) {
	tests := []struct {
		name   string
		counts OperationCounts
		want   int
	}{
		{
			name: "all operations",
			counts: OperationCounts{
				Added:    3,
				Modified: 2,
				Removed:  1,
				Renamed:  1,
			},
			want: 7,
		},
		{
			name:   "zero operations",
			counts: OperationCounts{},
			want:   0,
		},
		{
			name: "only added",
			counts: OperationCounts{
				Added: 5,
			},
			want: 5,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := tt.counts.Total()
			if got != tt.want {
				t.Errorf("Total() = %d, want %d", got, tt.want)
			}
		})
	}
}
